apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sinatra-base
  labels:
    app: app-sinatra-base
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-sinatra-base
  template:
    metadata:
      labels:
        app: app-sinatra-base
    spec:
      containers:
      - name: app-sinatra-base
        image: app-base-sinatra
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: app-base-sinatra
  labels:
    app: app-base-sinatra
spec:
  selector:
    app: app-base-sinatra
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4567
