source 'https://rubygems.org'

gem 'thin', '~> 1.7', '>= 1.7.2'
gem 'sqlite3', '~> 1.4', '>= 1.4.2'
gem 'rake', '~> 13.0', '>= 13.0.1'
gem 'activerecord', '~> 6.0', '>= 6.0.2.2'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.18'
gem 'sinatra', '~> 2.0', '>= 2.0.8.1'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.8.1'
gem 'require_all', '~> 3.0'
gem 'faye-websocket', '~> 0.10.9'
gem 'jwt', '~> 2.2', '>= 2.2.1'
gem 'rotp', '~> 6.0'

group :development do
  gem 'rubocop', '~> 0.55'
  gem 'rspec', '~> 3.9'
  gem 'simplecov', '~> 0.18.5'
end